### ISSUE TITLE
Mendel software link is broken

### ISSUE THREAD

**Issue by LZarri** [eriqande/CKMRsim#2]
I haven't been able to track down the software with a google search, and the link in the [original citing paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3673222/) is broken. I've emailed the author for a new link but wanted to let you know as well

**Comment by lerch-a** [comment]
I do have the same issues with the Mendel software link. Are there any updates?

**Comment by LZarri** [comment]
Here is a Dropbox link to the software for PC https://www.dropbox.com/s/ldql504smky6ggs/Mendel-160-win-setup.exe

**Comment by eriqande** [comment]
Thanks Liam for posting that.

I spoke to Eric Sobel quite a while ago and had hoped that the link would
get fixed.  I have binaries for Mendel for most platforms.  I've been
meaning to ask Eric S. if I could post those somewhere and then just have
an R function that downloads them and puts them somewhere reliable.

eric
